import HC4.Valuation.AdaptiveAlignedSmithCanonicalStationaryPlanarCoreFinalAssemblyPostRigidMixedLayerCross
import HC4.Valuation.AdaptiveAlignedSmithCanonicalStationaryPlanarCoreFinalAssemblyRightRecenteredKernelExit
import HC4.Valuation.AdaptiveAlignedSmithCanonicalStationaryPlanarCoreCurvedElimination
import HC4.Valuation.NonlinearDegreeBoundPreservation
import Mathlib.Tactic

/-!
# Final assembly A17.3F: eliminate the source-complete rigid branch

The maximal rigid layer is `a L^D`, `D >= 2`, and A17.3C supplied the
explicit transverse vector `v = c_p e_q - c_q e_p` in `ker L`.

For every affine base point we restrict the honest four-variable special
fibre to the binary plane generated by `e_p` and `v`.  The full all-minors
certificate makes this binary restriction singular-Hessian.  Its nonlinear
top facet is the pure `X_0^D` facet.  After subtracting the harmless `X_1`
linear coefficient, the already-green finite first-contact rigidity theorem
forces the whole restriction to be independent of `X_1`.  Therefore the
second derivative in the `v` direction vanishes at every affine base point,
so it vanishes as a four-variable polynomial.

Finally the all-minors identity and the nonzero pivot top Hessian entry turn
`D_v^2 F = 0` into the full vector equation `Hess(F) v = 0`.  A17.3E then
spends this honest transverse constant kernel.  Hence the rigid constructor
is removed completely.
-/

namespace HC4.Valuation

noncomputable section

open HC4.Newton
open HC4.Polynomial
open MvPolynomial
open scoped Matrix BigOperators
open AdaptiveAlignedSmithRankOneClosingSourceCarrier

universe u
variable {K : Type u} [Field K] [CharZero K]

-- The finite `Fin 4` coordinate normalisations below deliberately discharge
-- a handful of 16/64-case algebraic identities.  Keep their elaboration local
-- to this assembly file rather than depending on the project-wide default.
set_option maxHeartbeats 1000000

/-- Sparse direction `c_p e_q - c_q e_p`. -/
def rigidPairDirection (c : Fin 4 → K) (p q : Fin 4) : Fin 4 → K :=
  fun i => if i = q then c p else if i = p then - c q else 0

/-- Affine binary slice in the plane generated by `e_p` and the sparse
kernel direction `c_p e_q - c_q e_p`. -/
def rigidTopBinaryPlaneSpecialisation
    (a c : Fin 4 → K) (p q : Fin 4) :
    MvPolynomial (Fin 4) K →+* MvPolynomial (Fin 2) K :=
  MvPolynomial.eval₂Hom MvPolynomial.C
    (fun i =>
      MvPolynomial.C (a i) +
        (if i = p then MvPolynomial.X (0 : Fin 2) else 0) +
        MvPolynomial.C (rigidPairDirection c p q i) *
          MvPolynomial.X (1 : Fin 2))

@[simp] theorem rigidTopBinaryPlaneSpecialisation_C
    (a c : Fin 4 → K) (p q : Fin 4) (z : K) :
    rigidTopBinaryPlaneSpecialisation a c p q (MvPolynomial.C z) =
      MvPolynomial.C z := by
  simp [rigidTopBinaryPlaneSpecialisation]

@[simp] theorem rigidTopBinaryPlaneSpecialisation_X
    (a c : Fin 4 → K) (p q i : Fin 4) :
    rigidTopBinaryPlaneSpecialisation a c p q (MvPolynomial.X i) =
      MvPolynomial.C (a i) +
        (if i = p then MvPolynomial.X (0 : Fin 2) else 0) +
        MvPolynomial.C (rigidPairDirection c p q i) *
          MvPolynomial.X (1 : Fin 2) := by
  simp [rigidTopBinaryPlaneSpecialisation]

/-- The sparse pair direction gives the expected ambient directional
first derivative.  This elementary identity is placed before the binary chain
rule so the latter never has to expand a four-term directional sum inside a
`Fin 4` case split. -/
theorem constantSourceDirectionalDerivative_rigidPairDirection
    (F : MvPolynomial (Fin 4) K) (c : Fin 4 → K)
    (p q : Fin 4) (hpq : p ≠ q) :
    constantSourceDirectionalDerivative F (rigidPairDirection c p q) =
      MvPolynomial.C (c p) * MvPolynomial.pderiv q F -
        MvPolynomial.C (c q) * MvPolynomial.pderiv p F := by
  unfold constantSourceDirectionalDerivative
  rw [Fin.sum_univ_four]
  fin_cases p <;> fin_cases q <;>
    simp [rigidPairDirection, Fin.sum_univ_four] at hpq ⊢ <;> ring

/-- First binary derivative of the affine slice is the ambient `p` partial. -/
theorem pderiv_zero_rigidTopBinaryPlaneSpecialisation
    (a c : Fin 4 → K) (p q : Fin 4) (hpq : p ≠ q)
    (F : MvPolynomial (Fin 4) K) :
    MvPolynomial.pderiv (0 : Fin 2)
        (rigidTopBinaryPlaneSpecialisation a c p q F) =
      rigidTopBinaryPlaneSpecialisation a c p q
        (MvPolynomial.pderiv p F) := by
  apply MvPolynomial.induction_on F
  · intro z
    simp [rigidTopBinaryPlaneSpecialisation]
  · intro P Q hP hQ
    simp [hP, hQ] <;> ring
  · intro P i hP
    simp only [map_mul, rigidTopBinaryPlaneSpecialisation_X,
      MvPolynomial.pderiv_mul, map_add, hP]
    fin_cases p <;> fin_cases q <;> fin_cases i <;>
      simp [rigidPairDirection] at hpq ⊢ <;> ring

/-- Second binary coordinate differentiates in the sparse top-kernel
direction. -/
theorem pderiv_one_rigidTopBinaryPlaneSpecialisation
    (a c : Fin 4 → K) (p q : Fin 4) (hpq : p ≠ q)
    (F : MvPolynomial (Fin 4) K) :
    MvPolynomial.pderiv (1 : Fin 2)
        (rigidTopBinaryPlaneSpecialisation a c p q F) =
      rigidTopBinaryPlaneSpecialisation a c p q
        (constantSourceDirectionalDerivative F (rigidPairDirection c p q)) := by
  rw [constantSourceDirectionalDerivative_rigidPairDirection F c p q hpq]
  apply MvPolynomial.induction_on F
  · intro z
    simp [rigidTopBinaryPlaneSpecialisation]
  · intro P Q hP hQ
    simp [hP, hQ] <;> ring
  · intro P i hP
    by_cases hiq : i = q
    · subst i
      simp [hP, rigidTopBinaryPlaneSpecialisation_X, rigidPairDirection,
        hpq, Ne.symm hpq, MvPolynomial.pderiv_mul] <;> ring
    · by_cases hip : i = p
      · subst i
        simp [hP, rigidTopBinaryPlaneSpecialisation_X, rigidPairDirection,
          hpq, Ne.symm hpq, MvPolynomial.pderiv_mul] <;> ring
      · simp [hP, rigidTopBinaryPlaneSpecialisation_X, rigidPairDirection,
          hiq, hip, MvPolynomial.pderiv_mul] <;> ring

/-- Evaluation of the affine slice is literal ambient affine evaluation. -/
theorem eval_rigidTopBinaryPlaneSpecialisation
    (a c : Fin 4 → K) (p q : Fin 4)
    (F : MvPolynomial (Fin 4) K) (t₀ t₁ : K) :
    MvPolynomial.eval (fun i : Fin 2 => if i = 0 then t₀ else t₁)
        (rigidTopBinaryPlaneSpecialisation a c p q F) =
      MvPolynomial.eval
        (fun i => a i + (if i = p then t₀ else 0) +
          rigidPairDirection c p q i * t₁) F := by
  apply MvPolynomial.induction_on F
  · intro z
    simp [rigidTopBinaryPlaneSpecialisation]
  · intro P Q hP hQ
    simp [hP, hQ]
  · intro P i hP
    simp only [map_mul, MvPolynomial.eval_mul, hP,
      rigidTopBinaryPlaneSpecialisation_X]
    fin_cases i <;> fin_cases p <;> fin_cases q <;>
      simp [rigidPairDirection] <;> ring

/-- The sparse direction used by A17.3C is exactly the pair direction. -/
theorem rigidTopKernelDirection_eq_rigidPairDirection
    (c : Fin 4 → K) (p : Fin 4) :
    rigidTopKernelDirection c p =
      rigidPairDirection c p (rigidTopTransverseIndex p) := by
  funext i
  simp [rigidTopKernelDirection, rigidPairDirection]

/-- The binary Hessian determinant of the rigid affine plane is the
square of the nonzero transverse scale times the ambient `(p,q)` minor. -/
theorem binaryDirectionalHessianDet_rigidTopBinaryPlaneSpecialisation
    (a c : Fin 4 → K) (p q : Fin 4) (hpq : p ≠ q)
    (F : MvPolynomial (Fin 4) K) :
    binaryDirectionalHessianDet (0 : Fin 2) 1
        (rigidTopBinaryPlaneSpecialisation a c p q F) =
      MvPolynomial.C ((c p) ^ 2) *
        rigidTopBinaryPlaneSpecialisation a c p q
          (HC4.Polynomial.hessian F p p * HC4.Polynomial.hessian F q q -
            HC4.Polynomial.hessian F p q * HC4.Polynomial.hessian F q p) := by
  let φ := rigidTopBinaryPlaneSpecialisation a c p q
  let v := rigidPairDirection c p q
  change binaryDirectionalHessianDet (0 : Fin 2) 1 (φ F) =
    MvPolynomial.C ((c p) ^ 2) *
      φ (HC4.Polynomial.hessian F p p * HC4.Polynomial.hessian F q q -
        HC4.Polynomial.hessian F p q * HC4.Polynomial.hessian F q p)
  have hφC (z : K) : φ (MvPolynomial.C z) = MvPolynomial.C z := by
    exact rigidTopBinaryPlaneSpecialisation_C a c p q z
  have h0 (G : MvPolynomial (Fin 4) K) :
      MvPolynomial.pderiv (0 : Fin 2) (φ G) = φ (MvPolynomial.pderiv p G) := by
    exact pderiv_zero_rigidTopBinaryPlaneSpecialisation a c p q hpq G
  have h1 (G : MvPolynomial (Fin 4) K) :
      MvPolynomial.pderiv (1 : Fin 2) (φ G) =
        φ (constantSourceDirectionalDerivative G v) := by
    exact pderiv_one_rigidTopBinaryPlaneSpecialisation a c p q hpq G
  have hv (G : MvPolynomial (Fin 4) K) :
      constantSourceDirectionalDerivative G v =
        MvPolynomial.C (c p) * MvPolynomial.pderiv q G -
          MvPolynomial.C (c q) * MvPolynomial.pderiv p G := by
    unfold constantSourceDirectionalDerivative
    rw [Fin.sum_univ_four]
    fin_cases p <;> fin_cases q <;>
      simp [v, rigidPairDirection] at hpq ⊢ <;> ring
  have h00 :
      directionalSecondDerivative (0 : Fin 2) (φ F) =
        φ (HC4.Polynomial.hessian F p p) := by
    unfold directionalSecondDerivative
    rw [h0, h0]
    rfl
  have h01 :
      directionalMixedDerivative (0 : Fin 2) 1 (φ F) =
        MvPolynomial.C (c p) * φ (HC4.Polynomial.hessian F p q) -
          MvPolynomial.C (c q) * φ (HC4.Polynomial.hessian F p p) := by
    unfold directionalMixedDerivative
    rw [h1, h0, hv]
    simp only [map_sub, MvPolynomial.pderiv_C_mul]
    simp only [map_sub, map_mul, hφC, HC4.Polynomial.hessian_apply]
    rw [pderiv_comm_commRing p q F]
  have h11 :
      directionalSecondDerivative (1 : Fin 2) (φ F) =
        MvPolynomial.C ((c p) ^ 2) * φ (HC4.Polynomial.hessian F q q) -
          MvPolynomial.C (c p * c q) * φ (HC4.Polynomial.hessian F q p) -
          MvPolynomial.C (c p * c q) * φ (HC4.Polynomial.hessian F p q) +
          MvPolynomial.C ((c q) ^ 2) * φ (HC4.Polynomial.hessian F p p) := by
    unfold directionalSecondDerivative
    rw [h1, h1, hv, hv]
    simp only [map_sub, MvPolynomial.pderiv_C_mul]
    simp only [map_sub, map_mul, hφC, MvPolynomial.C_mul,
      MvPolynomial.C_pow, HC4.Polynomial.hessian_apply]
    ring_nf
  have hsym : φ (HC4.Polynomial.hessian F q p) =
      φ (HC4.Polynomial.hessian F p q) := by
    apply congrArg φ
    exact pderiv_comm_commRing p q F
  unfold binaryDirectionalHessianDet
  rw [h00, h11, h01]
  simp only [map_sub, map_mul, hφC, MvPolynomial.C_mul,
    MvPolynomial.C_pow, hsym]
  ring_nf

/-- The top linear form is constant on the affine kernel direction and changes
only in binary coordinate `0`. -/
theorem rigidTopBinaryPlaneSpecialisation_gradientRatioLinearForm
    (a c : Fin 4 → K) (p q : Fin 4) (hpq : p ≠ q)
    (hbase : ∑ i : Fin 4, c i * a i = 0) :
    rigidTopBinaryPlaneSpecialisation a c p q
        (gradientRatioLinearForm c) =
      MvPolynomial.C (c p) * MvPolynomial.X (0 : Fin 2) := by
  unfold gradientRatioLinearForm
  simp only [map_sum, map_mul, rigidTopBinaryPlaneSpecialisation_C,
    rigidTopBinaryPlaneSpecialisation_X]
  have hbaseC :
      MvPolynomial.C (∑ i : Fin 4, c i * a i) =
        (0 : MvPolynomial (Fin 2) K) := by
    simpa using congrArg
      (fun z : K => (MvPolynomial.C z : MvPolynomial (Fin 2) K)) hbase
  rw [Fin.sum_univ_four] at hbaseC ⊢
  simp only [MvPolynomial.C_add, MvPolynomial.C_mul] at hbaseC
  fin_cases p <;> fin_cases q <;>
    simp [rigidPairDirection, Fin.sum_univ_four] at hpq ⊢ <;>
    ring_nf at hbaseC ⊢ <;> linear_combination hbaseC

/-- A `Fin 2` support exponent is bounded by total degree. -/
theorem finTwo_degree_le_totalDegree_of_mem_support
    (P : MvPolynomial (Fin 2) K) (d : Fin 2 →₀ ℕ)
    (hd : d ∈ P.support) : d.degree ≤ P.totalDegree := by
  have h := MvPolynomial.le_totalDegree hd
  have hsum : d.sum (fun _ e => e) = d 0 + d 1 := by
    rw [Finsupp.sum_fintype]
    · simp
    · intro i
      simp
  rw [finTwo_degree_eq_add_curved d, ← hsum]
  exact h

/-- Affine substitution by four source variables into binary affine linear
polynomials sends a monomial to degree at most its original ordinary degree. -/
theorem totalDegree_eval₂Hom_finTwo_monomial_le_ordinaryDegree4
    (g : Fin 4 → MvPolynomial (Fin 2) K)
    (hg : ∀ i, (g i).totalDegree ≤ 1)
    (n : Fin 4 →₀ ℕ) (z : K) :
    (MvPolynomial.eval₂Hom MvPolynomial.C g
      (MvPolynomial.monomial n z)).totalDegree ≤
        HC4.Polynomial.ordinaryDegree4 n := by
  classical
  rw [MvPolynomial.eval₂Hom_monomial]
  refine (MvPolynomial.totalDegree_mul _ _).trans ?_
  have hprod := MvPolynomial.totalDegree_finset_prod n.support
    (fun i => g i ^ n i)
  calc
    (MvPolynomial.C z).totalDegree +
        (n.prod fun i k => g i ^ k).totalDegree
        ≤ 0 + ∑ i ∈ n.support, (g i ^ n i).totalDegree := by
          apply Nat.add_le_add
          · simp
          · simpa [Finsupp.prod] using hprod
    _ ≤ ∑ i ∈ n.support, n i := by
      simp only [zero_add]
      exact Finset.sum_le_sum fun i hi =>
        (MvPolynomial.totalDegree_pow (g i) (n i)).trans
          (by simpa using Nat.mul_le_mul_left (n i) (hg i))
    _ = HC4.Polynomial.ordinaryDegree4 n := by
      rw [← finsuppSum_eq_ordinaryDegree4]
      simp [Finsupp.sum]

/-- Affine substitution into the rigid binary plane does not increase total
degree of an input monomial. -/
theorem totalDegree_rigidTopBinaryPlaneSpecialisation_monomial_le
    (a c : Fin 4 → K) (p q : Fin 4)
    (n : Fin 4 →₀ ℕ) (z : K) :
    (rigidTopBinaryPlaneSpecialisation a c p q
      (MvPolynomial.monomial n z)).totalDegree ≤
        HC4.Polynomial.ordinaryDegree4 n := by
  unfold rigidTopBinaryPlaneSpecialisation
  apply totalDegree_eval₂Hom_finTwo_monomial_le_ordinaryDegree4
  intro i
  have h0 : (MvPolynomial.C (a i) : MvPolynomial (Fin 2) K).totalDegree ≤ 1 := by
    simp
  have hp :
      ((if i = p then MvPolynomial.X (0 : Fin 2) else 0) :
        MvPolynomial (Fin 2) K).totalDegree ≤ 1 := by
    split <;> simp
  have hv :
      (MvPolynomial.C (rigidPairDirection c p q i) *
        MvPolynomial.X (1 : Fin 2) : MvPolynomial (Fin 2) K).totalDegree ≤ 1 := by
    exact (MvPolynomial.totalDegree_mul _ _).trans (by simp)
  exact (MvPolynomial.totalDegree_add _ _).trans
    (max_le ((MvPolynomial.totalDegree_add _ _).trans (max_le h0 hp)) hv)

/-- No support degree can increase under the rigid affine binary slice. -/
theorem rigidTopBinaryPlaneSpecialisation_support_degree_le
    (a c : Fin 4 → K) (p q : Fin 4)
    (F : MvPolynomial (Fin 4) K) (D : ℕ)
    (hmax : ∀ n ∈ F.support, HC4.Polynomial.ordinaryDegree4 n ≤ D) :
    ∀ d ∈ (rigidTopBinaryPlaneSpecialisation a c p q F).support,
      d.degree ≤ D := by
  classical
  intro d hd
  let φ := rigidTopBinaryPlaneSpecialisation a c p q
  have hsum :
      φ F = ∑ n ∈ F.support,
        φ (MvPolynomial.monomial n (MvPolynomial.coeff n F)) := by
    calc
      φ F = φ (∑ n ∈ F.support,
          MvPolynomial.monomial n (MvPolynomial.coeff n F)) := by
            exact congrArg φ (MvPolynomial.as_sum F)
      _ = _ := by simp only [map_sum]
  have hdSum : d ∈ (∑ n ∈ F.support,
      φ (MvPolynomial.monomial n (MvPolynomial.coeff n F))).support := by
    rwa [← hsum]
  have hdUnion := MvPolynomial.support_sum hdSum
  rcases Finset.mem_biUnion.mp hdUnion with ⟨n, hnF, hdn⟩
  have hdle := finTwo_degree_le_totalDegree_of_mem_support
    (φ (MvPolynomial.monomial n (MvPolynomial.coeff n F))) d hdn
  have hmono := totalDegree_rigidTopBinaryPlaneSpecialisation_monomial_le
    a c p q n (MvPolynomial.coeff n F)
  exact hdle.trans (hmono.trans (hmax n hnF))

/-- Strict source-degree version used for the remainder below the maximal
homogeneous layer. -/
theorem rigidTopBinaryPlaneSpecialisation_support_degree_lt
    (a c : Fin 4 → K) (p q : Fin 4)
    (F : MvPolynomial (Fin 4) K) (D : ℕ)
    (hlt : ∀ n ∈ F.support, HC4.Polynomial.ordinaryDegree4 n < D) :
    ∀ d ∈ (rigidTopBinaryPlaneSpecialisation a c p q F).support,
      d.degree < D := by
  classical
  intro d hd
  let φ := rigidTopBinaryPlaneSpecialisation a c p q
  have hsum :
      φ F = ∑ n ∈ F.support,
        φ (MvPolynomial.monomial n (MvPolynomial.coeff n F)) := by
    calc
      φ F = φ (∑ n ∈ F.support,
          MvPolynomial.monomial n (MvPolynomial.coeff n F)) := by
            exact congrArg φ (MvPolynomial.as_sum F)
      _ = _ := by simp only [map_sum]
  have hdSum : d ∈ (∑ n ∈ F.support,
      φ (MvPolynomial.monomial n (MvPolynomial.coeff n F))).support := by
    rwa [← hsum]
  have hdUnion := MvPolynomial.support_sum hdSum
  rcases Finset.mem_biUnion.mp hdUnion with ⟨n, hnF, hdn⟩
  have hdle := finTwo_degree_le_totalDegree_of_mem_support
    (φ (MvPolynomial.monomial n (MvPolynomial.coeff n F))) d hdn
  have hmono := totalDegree_rigidTopBinaryPlaneSpecialisation_monomial_le
    a c p q n (MvPolynomial.coeff n F)
  exact lt_of_le_of_lt (hdle.trans hmono) (hlt n hnF)

/-- Absence of binary support using coordinate `j` is exactly vanishing of the
`j` partial derivative. -/
theorem pderiv_eq_zero_of_no_binaryOutsideSupport
    (Q : MvPolynomial (Fin 2) K) (j : Fin 2)
    (hno : ¬ (binaryOutsideSupport j Q).Nonempty) :
    MvPolynomial.pderiv j Q = 0 := by
  ext m
  rw [coeff_pderiv_backport]
  have hcoeff :
      MvPolynomial.coeff (m + Finsupp.single j 1) Q = 0 := by
    by_contra hne
    apply hno
    refine ⟨m + Finsupp.single j 1, ?_⟩
    apply mem_binaryOutsideSupport.mpr
    refine ⟨MvPolynomial.mem_support_iff.mpr hne, ?_⟩
    simp [Finsupp.single_apply]
  rw [hcoeff]
  simp


/-- Remove exactly the transverse linear coefficient from a binary polynomial. -/
def killBinaryTransverseLinear
    (Q : MvPolynomial (Fin 2) K) : MvPolynomial (Fin 2) K :=
  Q - MvPolynomial.C (MvPolynomial.coeff (Finsupp.single (1 : Fin 2) 1) Q) *
    MvPolynomial.X (1 : Fin 2)

@[simp] theorem killBinaryTransverseLinear_linearCoeff
    (Q : MvPolynomial (Fin 2) K) :
    MvPolynomial.coeff (Finsupp.single (1 : Fin 2) 1)
      (killBinaryTransverseLinear Q) = 0 := by
  unfold killBinaryTransverseLinear
  rw [MvPolynomial.coeff_sub]
  simp [Finsupp.single_apply]

/-- Killing a linear term does not change the binary Hessian determinant. -/
theorem binaryDirectionalHessianDet_killBinaryTransverseLinear
    (Q : MvPolynomial (Fin 2) K) :
    binaryDirectionalHessianDet (0 : Fin 2) 1
      (killBinaryTransverseLinear Q) =
    binaryDirectionalHessianDet (0 : Fin 2) 1 Q := by
  unfold killBinaryTransverseLinear binaryDirectionalHessianDet
  unfold directionalSecondDerivative directionalMixedDerivative
  simp only [map_sub, MvPolynomial.pderiv_C_mul]
  simp [Finsupp.single_apply]

/-- The killed linear monomial has degree exactly one when it is present. -/
theorem degree_eq_one_of_mem_support_C_mul_X_one
    (b : K) (d : Fin 2 →₀ ℕ)
    (hd : d ∈ (MvPolynomial.C b * MvPolynomial.X (1 : Fin 2) :
      MvPolynomial (Fin 2) K).support) :
    d.degree = 1 := by
  have hne := MvPolynomial.mem_support_iff.mp hd
  rw [MvPolynomial.coeff_C_mul] at hne
  have hx : MvPolynomial.coeff d
      (MvPolynomial.X (1 : Fin 2) : MvPolynomial (Fin 2) K) ≠ 0 := by
    intro hz
    apply hne
    rw [hz, mul_zero]
  have hdEqRev : Finsupp.single (1 : Fin 2) 1 = d := by
    rw [MvPolynomial.coeff_X'] at hx
    simpa using hx
  have hdEq : d = Finsupp.single (1 : Fin 2) 1 := hdEqRev.symm
  subst d
  rw [finTwo_degree_eq_add_curved]
  simp [Finsupp.single_apply]

/-- Killing a transverse linear coefficient preserves a degree-`D` support
bound once `D >= 1`. -/
theorem killBinaryTransverseLinear_support_degree_le
    (Q : MvPolynomial (Fin 2) K) (D : ℕ)
    (hD : 1 ≤ D)
    (hmax : ∀ d ∈ Q.support, d.degree ≤ D) :
    ∀ d ∈ (killBinaryTransverseLinear Q).support, d.degree ≤ D := by
  intro d hd
  have hu : d ∈ Q.support ∪
      (MvPolynomial.C (MvPolynomial.coeff (Finsupp.single (1 : Fin 2) 1) Q) *
        MvPolynomial.X (1 : Fin 2)).support := by
    exact MvPolynomial.support_sub (Fin 2) _ _ hd
  rcases Finset.mem_union.mp hu with hQ | hlin
  · exact hmax d hQ
  · rw [degree_eq_one_of_mem_support_C_mul_X_one _ d hlin]
    exact hD

/-- Killing a degree-one transverse term cannot create a new degree-`D`
transverse top monomial when `D >= 2`. -/
theorem killBinaryTransverseLinear_topFacet
    (Q : MvPolynomial (Fin 2) K) (D : ℕ)
    (hD : 2 ≤ D)
    (htop : ∀ d ∈ Q.support, d.degree = D → d (1 : Fin 2) = 0) :
    ∀ d ∈ (killBinaryTransverseLinear Q).support,
      d.degree = D → d (1 : Fin 2) = 0 := by
  intro d hd hdeg
  have hu : d ∈ Q.support ∪
      (MvPolynomial.C (MvPolynomial.coeff (Finsupp.single (1 : Fin 2) 1) Q) *
        MvPolynomial.X (1 : Fin 2)).support := by
    exact MvPolynomial.support_sub (Fin 2) _ _ hd
  rcases Finset.mem_union.mp hu with hQ | hlin
  · exact htop d hQ hdeg
  · have h1 := degree_eq_one_of_mem_support_C_mul_X_one _ d hlin
    omega

/-- For `D >= 2`, killing the transverse linear term does not change the
coefficient of `X_0^D`. -/
theorem coeff_single_zero_killBinaryTransverseLinear
    (Q : MvPolynomial (Fin 2) K) (D : ℕ) (hD : 2 ≤ D) :
    MvPolynomial.coeff (Finsupp.single (0 : Fin 2) D)
        (killBinaryTransverseLinear Q) =
      MvPolynomial.coeff (Finsupp.single (0 : Fin 2) D) Q := by
  unfold killBinaryTransverseLinear
  rw [MvPolynomial.coeff_sub]
  have hne : Finsupp.single (0 : Fin 2) D ≠
      Finsupp.single (1 : Fin 2) 1 := by
    intro h
    have h0 := DFunLike.congr_fun h (0 : Fin 2)
    simp [Finsupp.single_apply] at h0
    omega
  have hne' : Finsupp.single (1 : Fin 2) 1 ≠
      Finsupp.single (0 : Fin 2) D := Ne.symm hne
  simp [MvPolynomial.coeff_C_mul, MvPolynomial.coeff_X', hne']

/-- A pure top power plus a strictly lower-degree remainder has exactly the
expected pure top facet after affine binary slicing. -/
theorem rigidBinarySlice_top_data
    (a c : Fin 4 → K) (p q : Fin 4) (hpq : p ≠ q)
    (F H R : MvPolynomial (Fin 4) K) (D E : ℕ) (A : K)
    (hdecomp : F = H + R)
    (hH : H = MvPolynomial.C A *
      (gradientRatioLinearForm c) ^ D)
    (hbase : ∑ i : Fin 4, c i * a i = 0)
    (hRmax : ∀ n ∈ R.support, HC4.Polynomial.ordinaryDegree4 n ≤ E)
    (hED : E < D)
    (hA : A ≠ 0)
    (hcp : c p ≠ 0) :
    let P := rigidTopBinaryPlaneSpecialisation a c p q F
    let topScalar := A * (c p) ^ D
    (∀ d ∈ P.support, d.degree ≤ D) ∧
    (∀ d ∈ P.support, d.degree = D → d (1 : Fin 2) = 0) ∧
    MvPolynomial.coeff (Finsupp.single (0 : Fin 2) D) P = topScalar ∧
    topScalar ≠ 0 := by
  let φ := rigidTopBinaryPlaneSpecialisation a c p q
  let PR := φ R
  let topScalar := A * (c p) ^ D
  have hφL : φ (gradientRatioLinearForm c) =
      MvPolynomial.C (c p) * MvPolynomial.X (0 : Fin 2) := by
    exact rigidTopBinaryPlaneSpecialisation_gradientRatioLinearForm
      a c p q hpq hbase
  have hφH : φ H = MvPolynomial.C topScalar *
      MvPolynomial.X (0 : Fin 2) ^ D := by
    rw [hH, map_mul, rigidTopBinaryPlaneSpecialisation_C, map_pow, hφL]
    dsimp [topScalar]
    rw [mul_pow]
    simp only [MvPolynomial.C_pow, MvPolynomial.C_mul]
    ring
  have hPRlt : ∀ d ∈ PR.support, d.degree < D := by
    intro d hd
    have hle := rigidTopBinaryPlaneSpecialisation_support_degree_le
      a c p q R E hRmax d hd
    exact lt_of_le_of_lt hle hED
  have hPdecomp : φ F =
      MvPolynomial.C topScalar * MvPolynomial.X (0 : Fin 2) ^ D + PR := by
    rw [hdecomp, map_add, hφH]
  have htopSupport (d : Fin 2 →₀ ℕ)
      (hd : d ∈ (MvPolynomial.C topScalar *
        MvPolynomial.X (0 : Fin 2) ^ D : MvPolynomial (Fin 2) K).support) :
      d = Finsupp.single (0 : Fin 2) D := by
    have hne := MvPolynomial.mem_support_iff.mp hd
    rw [MvPolynomial.coeff_C_mul] at hne
    have hx : MvPolynomial.coeff d
        ((MvPolynomial.X (0 : Fin 2) : MvPolynomial (Fin 2) K) ^ D) ≠ 0 := by
      intro hz
      apply hne
      rw [hz, mul_zero]
    have hdEqRev : Finsupp.single (0 : Fin 2) D = d := by
      rw [MvPolynomial.coeff_X_pow] at hx
      simpa using hx
    exact hdEqRev.symm
  have hmaxP : ∀ d ∈ (φ F).support, d.degree ≤ D := by
    intro d hd
    rw [hPdecomp] at hd
    have hu := MvPolynomial.support_add hd
    rcases Finset.mem_union.mp hu with htop | hrem
    · have hdEq := htopSupport d htop
      subst d
      rw [finTwo_degree_eq_add_curved]
      simp [Finsupp.single_apply]
    · exact Nat.le_of_lt (hPRlt d hrem)
  have hfacet : ∀ d ∈ (φ F).support, d.degree = D → d (1 : Fin 2) = 0 := by
    intro d hd hdeg
    rw [hPdecomp] at hd
    have hu := MvPolynomial.support_add hd
    rcases Finset.mem_union.mp hu with htop | hrem
    · have hdEq := htopSupport d htop
      subst d
      simp [Finsupp.single_apply]
    · exact False.elim ((Nat.ne_of_lt (hPRlt d hrem)) hdeg)
  have hcoeffR : MvPolynomial.coeff (Finsupp.single (0 : Fin 2) D) PR = 0 := by
    by_contra hne
    have hmem := MvPolynomial.mem_support_iff.mpr hne
    have hlt := hPRlt _ hmem
    rw [finTwo_degree_eq_add_curved] at hlt
    simp [Finsupp.single_apply] at hlt
  have hcoeffTop :
      MvPolynomial.coeff (Finsupp.single (0 : Fin 2) D)
        (MvPolynomial.C topScalar * MvPolynomial.X (0 : Fin 2) ^ D) =
        topScalar := by
    simp [MvPolynomial.coeff_C_mul, MvPolynomial.coeff_X_pow]
  have hcoeffP : MvPolynomial.coeff (Finsupp.single (0 : Fin 2) D) (φ F) =
      topScalar := by
    rw [hPdecomp, MvPolynomial.coeff_add, hcoeffTop, hcoeffR, add_zero]
  have hscalar : topScalar ≠ 0 := mul_ne_zero hA (pow_ne_zero D hcp)
  exact ⟨hmaxP, hfacet, hcoeffP, hscalar⟩


/-- The second derivative in the sparse pair direction has the standard
quadratic Hessian expression. -/
theorem secondDirectionalDerivative_rigidPairDirection
    (F : MvPolynomial (Fin 4) K) (c : Fin 4 → K)
    (p q : Fin 4) (hpq : p ≠ q) :
    constantSourceDirectionalDerivative
        (constantSourceDirectionalDerivative F (rigidPairDirection c p q))
        (rigidPairDirection c p q) =
      MvPolynomial.C ((c p) ^ 2) * HC4.Polynomial.hessian F q q -
        MvPolynomial.C (c p * c q) * HC4.Polynomial.hessian F q p -
        MvPolynomial.C (c p * c q) * HC4.Polynomial.hessian F p q +
        MvPolynomial.C ((c q) ^ 2) * HC4.Polynomial.hessian F p p := by
  rw [constantSourceDirectionalDerivative_rigidPairDirection F c p q hpq]
  rw [constantSourceDirectionalDerivative_rigidPairDirection
    (MvPolynomial.C (c p) * MvPolynomial.pderiv q F -
      MvPolynomial.C (c q) * MvPolynomial.pderiv p F) c p q hpq]
  simp only [map_sub, MvPolynomial.pderiv_C_mul,
    MvPolynomial.C_mul, MvPolynomial.C_pow, HC4.Polynomial.hessian_apply]
  rw [pderiv_comm_commRing p q F]
  ring

/-- Rank-one all-minors plus a nonzero pivot entry upgrades vanishing of the
quadratic form in the sparse direction to the full Hessian-kernel equation. -/
theorem hessian_mulVec_rigidPairDirection_eq_zero_of_second_zero
    (F : MvPolynomial (Fin 4) K) (c : Fin 4 → K)
    (p q : Fin 4) (hpq : p ≠ q)
    (hall : ∀ i j k l : Fin 4,
      HC4.Polynomial.hessian F i j * HC4.Polynomial.hessian F k l -
        HC4.Polynomial.hessian F i l * HC4.Polynomial.hessian F k j = 0)
    (hpp_ne : HC4.Polynomial.hessian F p p ≠ 0)
    (hsecond :
      constantSourceDirectionalDerivative
          (constantSourceDirectionalDerivative F (rigidPairDirection c p q))
          (rigidPairDirection c p q) = 0) :
    (HC4.Polynomial.hessian F).mulVec
        (fun i => MvPolynomial.C (rigidPairDirection c p q i)) = 0 := by
  let A := HC4.Polynomial.hessian F p p
  let B := HC4.Polynomial.hessian F p q
  let C := HC4.Polynomial.hessian F q q
  let cp : MvPolynomial (Fin 4) K := MvPolynomial.C (c p)
  let cq : MvPolynomial (Fin 4) K := MvPolynomial.C (c q)
  have hsym : HC4.Polynomial.hessian F q p = B := by
    dsimp [B]
    exact pderiv_comm_commRing p q F
  have hminor : A * C - B * B = 0 := by
    have h := hall p p q q
    rw [hsym] at h
    simpa only [A, B, C] using h
  have hquad : cp ^ 2 * C - cp * cq * B - cp * cq * B + cq ^ 2 * A = 0 := by
    have hform := secondDirectionalDerivative_rigidPairDirection F c p q hpq
    rw [hsecond] at hform
    rw [hsym] at hform
    simpa only [A, B, C, cp, cq, MvPolynomial.C_mul,
      MvPolynomial.C_pow] using hform.symm
  have hsq : (cp * B - cq * A) * (cp * B - cq * A) = 0 := by
    calc
      (cp * B - cq * A) * (cp * B - cq * A) =
          A * (cp ^ 2 * C - cp * cq * B - cp * cq * B + cq ^ 2 * A) -
            cp ^ 2 * (A * C - B * B) := by ring
      _ = 0 := by rw [hquad, hminor]; ring
  have hratio : cp * B - cq * A = 0 := by
    exact (mul_self_eq_zero.mp hsq)
  funext r
  have hrowMinor : A * HC4.Polynomial.hessian F r q -
      B * HC4.Polynomial.hessian F r p = 0 := by
    simpa only [A, B] using hall p p r q
  have hmul : A *
      (cp * HC4.Polynomial.hessian F r q -
        cq * HC4.Polynomial.hessian F r p) = 0 := by
    calc
      A * (cp * HC4.Polynomial.hessian F r q -
          cq * HC4.Polynomial.hessian F r p) =
        cp * (A * HC4.Polynomial.hessian F r q -
          B * HC4.Polynomial.hessian F r p) +
          (cp * B - cq * A) * HC4.Polynomial.hessian F r p := by ring
      _ = 0 := by rw [hrowMinor, hratio]; ring
  have hrow : cp * HC4.Polynomial.hessian F r q -
      cq * HC4.Polynomial.hessian F r p = 0 :=
    (mul_eq_zero.mp hmul).resolve_left (by simpa [A] using hpp_ne)
  simp only [Matrix.mulVec, dotProduct]
  rw [Fin.sum_univ_four]
  fin_cases p <;> fin_cases q <;> fin_cases r <;>
    simp [rigidPairDirection, cp, cq] at hpq hrow ⊢ <;>
    linear_combination hrow

/-- The pivot Hessian entry of the complete rigid special fibre is nonzero,
because its maximal homogeneous component has nonzero `pp` Hessian entry. -/
theorem AdaptiveAlignedSmithCanonicalRigidTopKernelData.full_pivotHessian_ne_zero
    {s : ScaleAwareAdaptiveGeometricRestartState (K := K)}
    {S : AdaptiveAlignedSmithCanonicalScaleSoundStationaryBlocker s}
    (T : AdaptiveAlignedSmithCanonicalRigidTopKernelData S) :
    HC4.Polynomial.hessian
      (longitudinalRightRecenterHom
        (K := K) S.blocker.aligned.endpoint.rawSpecialFiber)
      T.pivot T.pivot ≠ 0 := by
  let F := longitudinalRightRecenterHom
    (K := K) S.blocker.aligned.endpoint.rawSpecialFiber
  let c := T.topLayer.ratio
  let p := T.pivot
  obtain ⟨n, hD⟩ : ∃ n : ℕ, T.topLayer.degree = n + 2 := by
    exact ⟨T.topLayer.degree - 2,
      (Nat.sub_add_cancel T.topLayer.degree_ge_two).symm⟩
  have hA : T.topLayer.coefficient ≠ 0 := by
    intro hzero
    apply T.topLayer.top_ne_zero
    rw [T.topLayer.linearPower, hzero]
    simp
  have hL : gradientRatioLinearForm c ≠ 0 := by
    intro hzero
    have h := congrArg (MvPolynomial.pderiv p) hzero
    rw [pderiv_gradientRatioLinearForm_fin] at h
    simp at h
    exact T.pivot_ne_zero h
  have hn2 : (((n + 2 : ℕ) : K)) ≠ 0 := by
    exact_mod_cast Nat.succ_ne_zero (n + 1)
  have hn1 : (((n + 1 : ℕ) : K)) ≠ 0 := by
    exact_mod_cast Nat.succ_ne_zero n
  have hs : T.topLayer.coefficient * (((n + 2 : ℕ) : K)) *
      (((n + 1 : ℕ) : K)) * c p * c p ≠ 0 := by
    exact mul_ne_zero
      (mul_ne_zero
        (mul_ne_zero
          (mul_ne_zero hA hn2) hn1)
        T.pivot_ne_zero)
      T.pivot_ne_zero
  have htoppp : HC4.Polynomial.hessian T.topLayer.top p p ≠ 0 := by
    have hformula :=
      hessian_C_mul_gradientRatioLinearForm_pow_add_two_finFour
        T.topLayer.coefficient c n p p
    have htopform : T.topLayer.top =
        MvPolynomial.C T.topLayer.coefficient *
          (gradientRatioLinearForm c) ^ (n + 2) := by
      rw [T.topLayer.linearPower, hD]
    rw [htopform, hformula]
    exact mul_ne_zero (MvPolynomial.C_ne_zero.mpr hs) (pow_ne_zero n hL)
  intro hfull
  have hinit := initialForm_fourHessianEntry_eq_componentHessian
    F T.topLayer.degree p p
  rw [hfull] at hinit
  simp only [initialForm_zero] at hinit
  have hcomp : fourOrdinaryDegreeComponent F T.topLayer.degree =
      T.topLayer.top := by
    simpa [F] using T.topLayer.top_eq.symm
  rw [hcomp] at hinit
  exact htoppp hinit.symm


namespace AdaptiveAlignedSmithCanonicalRigidMixedLayerCrossData

/-- Every affine binary slice in the canonical top-kernel plane has zero
second derivative in the transverse slice coordinate. -/
theorem secondDirectionalDerivative_eq_zero
    {s : ScaleAwareAdaptiveGeometricRestartState (K := K)}
    {S : AdaptiveAlignedSmithCanonicalScaleSoundStationaryBlocker s}
    (T : AdaptiveAlignedSmithCanonicalRigidMixedLayerCrossData S) :
    let F := longitudinalRightRecenterHom
      (K := K) S.blocker.aligned.endpoint.rawSpecialFiber
    let c := T.topKernel.topLayer.ratio
    let p := T.topKernel.pivot
    let q := rigidTopTransverseIndex p
    constantSourceDirectionalDerivative
        (constantSourceDirectionalDerivative F (rigidPairDirection c p q))
        (rigidPairDirection c p q) = 0 := by
  let F := longitudinalRightRecenterHom
    (K := K) S.blocker.aligned.endpoint.rawSpecialFiber
  let H := T.topKernel.topLayer.top
  let R := T.remainder
  let D := T.topKernel.topLayer.degree
  let E := T.degree
  let c := T.topKernel.topLayer.ratio
  let p := T.topKernel.pivot
  let q := rigidTopTransverseIndex p
  let v := rigidPairDirection c p q
  have hpq : p ≠ q := by
    exact Ne.symm (rigidTopTransverseIndex_ne_pivot p)
  have hcp : c p ≠ 0 := by
    simpa [c, p] using T.topKernel.pivot_ne_zero
  have hD : 2 ≤ D := by
    simpa [D] using T.topKernel.topLayer.degree_ge_two
  have hA : T.topKernel.topLayer.coefficient ≠ 0 := by
    intro hzero
    apply T.topKernel.topLayer.top_ne_zero
    rw [T.topKernel.topLayer.linearPower, hzero]
    simp
  have hdecomp : F = H + R := by
    have hR := T.remainder_eq
    dsimp [F, H, R] at hR ⊢
    rw [hR]
    ring
  have hH : H = MvPolynomial.C T.topKernel.topLayer.coefficient *
      (gradientRatioLinearForm c) ^ D := by
    simpa [H, c, D] using T.topKernel.topLayer.linearPower
  have hED : E < D := by
    simpa [E, D] using T.degree_lt_top
  have hRmax : ∀ n ∈ R.support,
      HC4.Polynomial.ordinaryDegree4 n ≤ E := by
    simpa [R, E] using T.remainder_maximal
  have hall : ∀ i j k l : Fin 4,
      HC4.Polynomial.hessian F i j * HC4.Polynomial.hessian F k l -
        HC4.Polynomial.hessian F i l * HC4.Polynomial.hessian F k j = 0 := by
    simpa [F] using T.topKernel.topLayer.rigid.raw_allMinors

  apply MvPolynomial.funext
  intro x
  let alpha : K := (∑ i : Fin 4, c i * x i) / c p
  let a : Fin 4 → K := fun i => x i - if i = p then alpha else 0
  let phi := rigidTopBinaryPlaneSpecialisation a c p q
  let P : MvPolynomial (Fin 2) K := phi F
  let N : MvPolynomial (Fin 2) K := killBinaryTransverseLinear P

  have hbase : ∑ i : Fin 4, c i * a i = 0 := by
    dsimp [a, alpha]
    have hfin4 : ∀ r : Fin 4,
        r = (0 : Fin 4) ∨ r = 1 ∨ r = 2 ∨ r = 3 := by
      intro r
      fin_cases r <;> simp
    rcases hfin4 p with hp0 | hp1 | hp2 | hp3
    · have hcp0 : c (0 : Fin 4) ≠ 0 := by simpa [hp0] using hcp
      rw [hp0, Fin.sum_univ_four, Fin.sum_univ_four]
      simp <;> field_simp [hcp0] <;> ring
    · have hcp1 : c (1 : Fin 4) ≠ 0 := by simpa [hp1] using hcp
      rw [hp1, Fin.sum_univ_four, Fin.sum_univ_four]
      simp <;> field_simp [hcp1] <;> ring
    · have hcp2 : c (2 : Fin 4) ≠ 0 := by simpa [hp2] using hcp
      rw [hp2, Fin.sum_univ_four, Fin.sum_univ_four]
      simp <;> field_simp [hcp2] <;> ring
    · have hcp3 : c (3 : Fin 4) ≠ 0 := by simpa [hp3] using hcp
      rw [hp3, Fin.sum_univ_four, Fin.sum_univ_four]
      simp <;> field_simp [hcp3] <;> ring

  have htop := rigidBinarySlice_top_data
    a c p q hpq F H R D E T.topKernel.topLayer.coefficient
    hdecomp hH hbase hRmax hED hA hcp
  change
    (∀ d ∈ P.support, d.degree ≤ D) ∧
      (∀ d ∈ P.support, d.degree = D → d (1 : Fin 2) = 0) ∧
      MvPolynomial.coeff (Finsupp.single (0 : Fin 2) D) P =
        T.topKernel.topLayer.coefficient * (c p) ^ D ∧
      T.topKernel.topLayer.coefficient * (c p) ^ D ≠ 0 at htop
  rcases htop with ⟨hPmax, hPfacet, hPcoeff, hPcoeff_ne⟩

  have hPdet : binaryDirectionalHessianDet (0 : Fin 2) 1 P = 0 := by
    dsimp [P, phi]
    rw [binaryDirectionalHessianDet_rigidTopBinaryPlaneSpecialisation
      a c p q hpq F]
    rw [hall p p q q]
    simp
  have hNmax : ∀ d ∈ N.support, d.degree ≤ D := by
    dsimp [N]
    exact killBinaryTransverseLinear_support_degree_le P D
      (le_trans (by decide : 1 ≤ 2) hD) hPmax
  have hNfacet : ∀ d ∈ N.support,
      d.degree = D → d (1 : Fin 2) = 0 := by
    dsimp [N]
    exact killBinaryTransverseLinear_topFacet P D hD hPfacet
  have hNcoeff : MvPolynomial.coeff (Finsupp.single (0 : Fin 2) D) N ≠ 0 := by
    dsimp [N]
    rw [coeff_single_zero_killBinaryTransverseLinear P D hD, hPcoeff]
    exact hPcoeff_ne
  have hNlinear : MvPolynomial.coeff (Finsupp.single (1 : Fin 2) 1) N = 0 := by
    exact killBinaryTransverseLinear_linearCoeff P
  have hNdet : binaryDirectionalHessianDet (0 : Fin 2) 1 N = 0 := by
    dsimp [N]
    rw [binaryDirectionalHessianDet_killBinaryTransverseLinear]
    exact hPdet
  have hno : ¬ (binaryOutsideSupport (1 : Fin 2) N).Nonempty := by
    exact binarySingularHessian_no_outsideSupport_of_pureTop
      N D (0 : Fin 2) 1 (by decide) hD hNmax hNfacet hNcoeff hNlinear hNdet
  have hNderiv : MvPolynomial.pderiv (1 : Fin 2) N = 0 :=
    pderiv_eq_zero_of_no_binaryOutsideSupport N 1 hno
  have hsecondP :
      MvPolynomial.pderiv (1 : Fin 2)
        (MvPolynomial.pderiv (1 : Fin 2) P) = 0 := by
    have h := congrArg (MvPolynomial.pderiv (1 : Fin 2)) hNderiv
    simpa [N, killBinaryTransverseLinear] using h
  have hslice :
      phi (constantSourceDirectionalDerivative
        (constantSourceDirectionalDerivative F v) v) = 0 := by
    have hfirst := pderiv_one_rigidTopBinaryPlaneSpecialisation
      a c p q hpq F
    have hsecond := pderiv_one_rigidTopBinaryPlaneSpecialisation
      a c p q hpq (constantSourceDirectionalDerivative F v)
    change MvPolynomial.pderiv (1 : Fin 2) P =
      phi (constantSourceDirectionalDerivative F v) at hfirst
    rw [hfirst] at hsecondP
    rw [hsecond] at hsecondP
    exact hsecondP

  have hpoint :
      (fun i => a i + (if i = p then alpha else 0) +
        rigidPairDirection c p q i * (0 : K)) = x := by
    funext i
    simp [a]
  have heval :
      MvPolynomial.eval x
        (constantSourceDirectionalDerivative
          (constantSourceDirectionalDerivative F v) v) = 0 := by
    calc
      MvPolynomial.eval x
          (constantSourceDirectionalDerivative
            (constantSourceDirectionalDerivative F v) v) =
        MvPolynomial.eval
          (fun i => a i + (if i = p then alpha else 0) +
            rigidPairDirection c p q i * (0 : K))
          (constantSourceDirectionalDerivative
            (constantSourceDirectionalDerivative F v) v) := by rw [hpoint]
      _ = MvPolynomial.eval
          (fun i : Fin 2 => if i = 0 then alpha else (0 : K))
          (phi (constantSourceDirectionalDerivative
            (constantSourceDirectionalDerivative F v) v)) := by
            symm
            exact eval_rigidTopBinaryPlaneSpecialisation
              a c p q
              (constantSourceDirectionalDerivative
                (constantSourceDirectionalDerivative F v) v)
              alpha 0
      _ = 0 := by rw [hslice]; simp
  simpa [v] using heval

/-- **A17.3F rigid kernel globalisation.**  The canonical transverse top-layer
kernel is a literal constant kernel of the complete honest rigid special-fibre
Hessian. -/
theorem toRightRecenteredConstantKernelData
    {s : ScaleAwareAdaptiveGeometricRestartState (K := K)}
    {S : AdaptiveAlignedSmithCanonicalScaleSoundStationaryBlocker s}
    (T : AdaptiveAlignedSmithCanonicalRigidMixedLayerCrossData S) :
    Nonempty (AdaptiveAlignedSmithCanonicalRightRecenteredConstantKernelData S) := by
  let F := longitudinalRightRecenterHom
    (K := K) S.blocker.aligned.endpoint.rawSpecialFiber
  let c := T.topKernel.topLayer.ratio
  let p := T.topKernel.pivot
  let q := rigidTopTransverseIndex p
  let v := rigidPairDirection c p q
  have hpq : p ≠ q := Ne.symm (rigidTopTransverseIndex_ne_pivot p)
  have hall : ∀ i j k l : Fin 4,
      HC4.Polynomial.hessian F i j * HC4.Polynomial.hessian F k l -
        HC4.Polynomial.hessian F i l * HC4.Polynomial.hessian F k j = 0 := by
    simpa [F] using T.topKernel.topLayer.rigid.raw_allMinors
  have hsecond :
      constantSourceDirectionalDerivative
          (constantSourceDirectionalDerivative F v) v = 0 := by
    simpa [F, c, p, q, v] using T.secondDirectionalDerivative_eq_zero
  have hpp : HC4.Polynomial.hessian F p p ≠ 0 := by
    simpa [F, p] using T.topKernel.full_pivotHessian_ne_zero
  have hkernelRaw :
      (HC4.Polynomial.hessian F).mulVec
        (fun i => MvPolynomial.C (v i)) = 0 :=
    hessian_mulVec_rigidPairDirection_eq_zero_of_second_zero
      F c p q hpq hall hpp hsecond
  have hvEq : v = T.topKernel.direction := by
    rw [T.topKernel.direction_eq,
      rigidTopKernelDirection_eq_rigidPairDirection]
  have hvne : v ≠ 0 := by
    rw [hvEq]
    exact T.topKernel.direction_ne_zero
  have htrans : ∃ ell : Fin 4, ell ≠ (0 : Fin 4) ∧ v ell ≠ 0 := by
    refine ⟨q, rigidTopTransverseIndex_ne_zero p, ?_⟩
    rw [hvEq]
    have hq : T.topKernel.transverse = q := by
      simpa [q] using T.topKernel.transverse_eq
    rw [← hq]
    exact T.topKernel.direction_transverse_ne_zero
  have hkernelActual :
      (HC4.Polynomial.hessian
        (polynomialFamilySpecialFiber
          S.blocker.aligned.endpoint.rightRecenteredFamily)).mulVec
        (fun i => MvPolynomial.C (v i)) = 0 := by
    rw [S.blocker.aligned.endpoint.rightRecenteredFamily_specialFiber]
    simpa [F] using hkernelRaw
  exact ⟨{
    direction := v
    direction_ne_zero := hvne
    transverse := htrans
    kernel := hkernelActual
  }⟩

/-- The rigid mixed-layer branch is therefore immediately spendable by the
blocker-native A17.3E exit. -/
theorem exists_ramifiedSpend
    {s : ScaleAwareAdaptiveGeometricRestartState (K := K)}
    (S : AdaptiveAlignedSmithCanonicalScaleSoundStationaryBlocker s)
    (clock_eq :
      S.blocker.aligned.endpoint.defect =
        alignedSmithRamificationIndex * s.rawDefect)
    (T : AdaptiveAlignedSmithCanonicalRigidMixedLayerCrossData S) :
    ∃ target : ScaleAwareAdaptiveGeometricRestartState (K := K),
      AdaptiveAlignedSmithBlockerClockProvenance.HasCertifiedRamifiedRawDefectSpend
        target s := by
  rcases T.toRightRecenteredConstantKernelData with ⟨D⟩
  exact D.exists_ramifiedSpend S clock_eq

end AdaptiveAlignedSmithCanonicalRigidMixedLayerCrossData

end

end HC4.Valuation