import HC4.Valuation.AdaptiveAlignedSmithRankOneSchurKernelProvenanceAssembly
import HC4.Valuation.AdaptiveAlignedSmithRankOneSchurCorrectedRS2Fork
import Mathlib.Tactic

/-!
# Stage 4B32: the correct projective target is the raw binary Schur line

The first-key/RS2 development was initially phrased using projective wedges
of the complete four-component cleared Hessian-kernel lift.  That target is
stronger than the Schur endgame actually needs: even when the binary Schur
kernel line is constant, the active-block elimination used by
`clearedKernelLift` may make the four lifted coordinates vary polynomially.

The source-honest object controlled by the rank-one Schur geometry is instead
the raw special binary block

    [[A, B], [B, C]]

before the polynomial-valued alignment.  In the left-pivot branch `A != 0`
and `A*C = B^2`, so its kernel is generated by `(-B,A)`.  Thus the genuine
projective obstruction is simply

    A * d_k B - B * d_k A.

If all four source wedges vanish, the already-green four-variable
logarithmic-derivative rigidity theorem gives

    B = c A

for one scalar `c : K`.  The determinant-zero relation then forces

    C = c^2 A,

so `(-c,1)` is a *constant* kernel line of the raw special Schur block.  The
right-axis pivot has the constant line `(1,0)` from the outset.

This file packages precisely that binary constant-line certificate and a
canonical denominator-cleared Schur kernel built from it.  Consequently the
remaining graded RS2 theorem only has to prove

    nonzero raw binary projective wedge -> certified repair.

It no longer has to prove projective constancy of the entire four-component
lift, and therefore no artificial first-projective-layer filtration of that
lift is needed.

No parameter order is identified with the spatial first-key order here.
-/

namespace HC4.Valuation

noncomputable section

open HC4.Newton
open HC4.Polynomial

variable {K : Type*} [Field K] [CharZero K]

namespace AdaptiveAlignedSmithRankOneClosingSourceCarrier

variable {degreeCap : ℕ}
variable {B : AdaptiveAlignedSmithBlockerEndpoint (K := K) degreeCap}

/-- One denominator-free projective wedge of the raw special binary Schur
kernel line.  In a left pivot this is the numerator of `d_k (B/A)`. -/
def rawSpecialSchurProjectiveWedge
    (C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B)
    (k : Fin 4) : MvPolynomial (Fin 4) K :=
  C.specialFourBlock.schurA *
      MvPolynomial.pderiv k C.specialFourBlock.schurB -
    C.specialFourBlock.schurB *
      MvPolynomial.pderiv k C.specialFourBlock.schurA

/-- The raw rank-one Schur kernel line is infinitesimally constant in all
four honest source directions. -/
def HasVanishingRawSpecialSchurProjectiveWedges
    (C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B) : Prop :=
  ∀ k : Fin 4, C.rawSpecialSchurProjectiveWedge k = 0

/-- A genuinely constant kernel line of the raw special binary Schur block.
This is deliberately weaker than a constant projective direction for the
complete four-component kernel lift. -/
structure ConstantSpecialSchurKernelLineData
    (C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B) where
  u : K
  v : K
  binary_ne_zero : u ≠ 0 ∨ v ≠ 0
  kernel :
    C.specialFourBlock.IsClearedSchurKernel
      (MvPolynomial.C u) (MvPolynomial.C v)

namespace ConstantSpecialSchurKernelLineData

variable {C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B}

/-- A constant raw binary Schur line is itself legitimate Stage-3
`DenominatorClearedSpecialSchurKernelData`.  The subsequent source-kernel
transport can therefore be run using this constant binary representative. -/
noncomputable def toDenominatorClearedSpecialSchurKernelData
    (L : C.ConstantSpecialSchurKernelLineData) :
    C.DenominatorClearedSpecialSchurKernelData where
  u := MvPolynomial.C L.u
  v := MvPolynomial.C L.v
  binary_ne_zero := by
    rcases L.binary_ne_zero with hu | hv
    · left
      simpa using hu
    · right
      simpa using hv
  schurKernel := L.kernel

end ConstantSpecialSchurKernelLineData

/-! ## Raw special entries versus the parameter-zero Schur coefficients -/

private theorem specialFourBlock_schurA_eq_raw_coeff_zero
    (C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B) :
    C.specialFourBlock.schurA =
      C.chartData.schurData.block.polynomialSchurSeries.active.coeff 0 := by
  simpa [AdaptiveAlignedSmithRankOneClosingSourceCarrier.specialFourBlock,
    GeneralFourBlock.polynomialSchurSeries] using
    (parameterConstantCoeffFourBlock_schurA C.chartData.schurData.block).symm

private theorem specialFourBlock_schurB_eq_raw_coeff_zero
    (C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B) :
    C.specialFourBlock.schurB =
      C.chartData.schurData.block.polynomialSchurSeries.offDiag.coeff 0 := by
  simpa [AdaptiveAlignedSmithRankOneClosingSourceCarrier.specialFourBlock,
    GeneralFourBlock.polynomialSchurSeries] using
    (parameterConstantCoeffFourBlock_schurB C.chartData.schurData.block).symm

private theorem specialFourBlock_schurC_eq_raw_coeff_zero
    (C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B) :
    C.specialFourBlock.schurC =
      C.chartData.schurData.block.polynomialSchurSeries.kernel.coeff 0 := by
  simpa [AdaptiveAlignedSmithRankOneClosingSourceCarrier.specialFourBlock,
    GeneralFourBlock.polynomialSchurSeries] using
    (parameterConstantCoeffFourBlock_schurC C.chartData.schurData.block).symm

/-! ## Vanishing raw wedges force one constant Schur line -/

/-- Left-pivot case: vanishing raw projective wedges make `B/A` one scalar
`c`, and the rank-one determinant relation then gives `C/A = c^2`.
Consequently `(-c,1)` is a constant raw Schur-kernel direction. -/
theorem constantSpecialSchurKernelLineData_of_left_of_vanishingWedges
    (C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B)
    (hleft :
      C.chartData.schurData.block.polynomialSchurSeries.LeftPivot)
    (hvanish : C.HasVanishingRawSpecialSchurProjectiveWedges) :
    Nonempty C.ConstantSpecialSchurKernelLineData := by
  let A : MvPolynomial (Fin 4) K := C.specialFourBlock.schurA
  let M : MvPolynomial (Fin 4) K := C.specialFourBlock.schurB
  let N : MvPolynomial (Fin 4) K := C.specialFourBlock.schurC

  have hAeq := C.specialFourBlock_schurA_eq_raw_coeff_zero
  have hMeq := C.specialFourBlock_schurB_eq_raw_coeff_zero
  have hNeq := C.specialFourBlock_schurC_eq_raw_coeff_zero

  have hA : A ≠ 0 := by
    dsimp [A]
    rw [hAeq]
    exact hleft.1

  have hcross :
      ∀ k : Fin 4,
        A * MvPolynomial.pderiv k M =
          M * MvPolynomial.pderiv k A := by
    intro k
    have hk := hvanish k
    change
      C.specialFourBlock.schurA *
          MvPolynomial.pderiv k C.specialFourBlock.schurB -
        C.specialFourBlock.schurB *
          MvPolynomial.pderiv k C.specialFourBlock.schurA = 0 at hk
    exact sub_eq_zero.mp (by simpa [A, M] using hk)

  rcases mvPolynomial_fin4_eq_C_mul_of_logDerivative_cross A M hA hcross with
    ⟨c, hM⟩

  have hdet : A * N = M * M := by
    dsimp [A, M, N]
    rw [hAeq, hMeq, hNeq]
    exact hleft.2

  have hN : N = MvPolynomial.C (c ^ 2) * A := by
    have hprod :
        A * (N - MvPolynomial.C (c ^ 2) * A) = 0 := by
      calc
        A * (N - MvPolynomial.C (c ^ 2) * A) =
            A * N - A * (MvPolynomial.C (c ^ 2) * A) := by ring
        _ = M * M - A * (MvPolynomial.C (c ^ 2) * A) := by rw [hdet]
        _ = 0 := by
          rw [hM]
          simp only [MvPolynomial.C_pow]
          ring
    have hdiff : N - MvPolynomial.C (c ^ 2) * A = 0 :=
      (mul_eq_zero.mp hprod).resolve_left hA
    exact sub_eq_zero.mp hdiff

  refine ⟨{
    u := -c
    v := 1
    binary_ne_zero := Or.inr one_ne_zero
    kernel := ?_
  }⟩
  unfold GeneralFourBlock.IsClearedSchurKernel
  constructor
  · dsimp [A, M] at hM
    rw [hM]
    simp
    ring
  · dsimp [M, N] at hM hN
    rw [hM, hN]
    simp only [map_neg, map_one, mul_one, MvPolynomial.C_pow]
    ring

/-- The right-axis pivot already has the constant raw kernel direction
`(1,0)`; no RS2 argument is needed in this branch. -/
theorem constantSpecialSchurKernelLineData_of_right
    (C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B)
    (hright :
      C.chartData.schurData.block.polynomialSchurSeries.RightAxisPivot) :
    Nonempty C.ConstantSpecialSchurKernelLineData := by
  have hAeq := C.specialFourBlock_schurA_eq_raw_coeff_zero
  have hBeq := C.specialFourBlock_schurB_eq_raw_coeff_zero
  refine ⟨{
    u := 1
    v := 0
    binary_ne_zero := Or.inl one_ne_zero
    kernel := ?_
  }⟩
  unfold GeneralFourBlock.IsClearedSchurKernel
  constructor
  · rw [hAeq, hBeq, hright.1, hright.2.1]
    simp
  · rw [hBeq, hright.2.1]
    simp

/-- **Correct binary projective dichotomy.**

Every retained rank-one special Schur block either has a genuinely nonzero
raw source projective wedge, or it already admits a constant binary kernel
line over `K`.

This is the exact target required from the remaining first-key/RS2 bridge;
there is no need to projectivise the complete four-component lifted kernel. -/
theorem rawSpecialSchurProjectiveWedge_or_constantLine
    (C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B) :
    (∃ k : Fin 4, C.rawSpecialSchurProjectiveWedge k ≠ 0) ∨
      Nonempty C.ConstantSpecialSchurKernelLineData := by
  by_cases hvanish : C.HasVanishingRawSpecialSchurProjectiveWedges
  · right
    generalize hp : C.chartData.schurData.chosenPivot = p
    cases p with
    | left hleft =>
        exact C.constantSpecialSchurKernelLineData_of_left_of_vanishingWedges
          hleft hvanish
    | right hright =>
        exact C.constantSpecialSchurKernelLineData_of_right hright
  · left
    unfold HasVanishingRawSpecialSchurProjectiveWedges at hvanish
    push_neg at hvanish
    exact hvanish

/-- Once the constant-line branch is reached, the B30 first-key descent may
be rerun using a denominator-cleared Schur kernel whose *binary* coordinates
are literally constant.  This is the provenance package the final assembly
will want on the null-RS2 branch. -/
theorem HasFirstTransverseSourceKey.exists_canonicalRS2ProvenanceAssemblyData_of_constantLine
    {C : AdaptiveAlignedSmithRankOneClosingSourceCarrier B}
    (hkey : C.HasFirstTransverseSourceKey)
    (L : C.ConstantSpecialSchurKernelLineData) :
    Nonempty C.FirstKeyCanonicalRS2ProvenanceAssemblyData := by
  exact
    hkey.exists_canonicalRS2ProvenanceAssemblyData
      L.toDenominatorClearedSpecialSchurKernelData

end AdaptiveAlignedSmithRankOneClosingSourceCarrier

end

end HC4.Valuation
