import HC4.Toric
import HC4.Polynomial
import HC4.Newton
import HC4.ClassifiedFamilies
import HC4.MainAssembly

import HC4.Valuation.CanonicalEntrySanity
import HC4.Valuation.CanonicalAdaptiveSmithWall

-- Current final-assembly theorem fronts.  These stay on the root graph so CI
-- checks both the well-founded A18.4 trace and the A18.5 rank-three closure.
import HC4.Valuation.AdaptiveAlignedSmithCanonicalRankOneTerminationTrace
import HC4.Valuation.AdaptiveAlignedSmithCanonicalTerminalSupportFrontier
import HC4.RationalRigidity.RankThreeBalancedHomogeneousImpossible
import HC4.Valuation.AdaptiveAlignedSmithCanonicalTerminalRigidityData
import HC4.Newton.FirstContactAffinePlane
import HC4.Newton.FirstContactHonestSlice
import HC4.Newton.FiniteSupportCrossFacetExposure
import HC4.Newton.FirstContactCrossFacetAffineLine
import HC4.Newton.FirstContactCrossFacetEndpointStratum
import HC4.Newton.FirstContactCrossFacetAffineRR
import HC4.Newton.FirstContactCrossFacetAffineRRReconstruction
import HC4.Newton.FirstContactCrossFacetAffineRRTerminal
import HC4.Newton.FirstContactCrossFacetAffineRRFiniteSplit
import HC4.Newton.FirstContactCrossFacetAffineRRTransition
import HC4.RationalRigidity.RankThreeAffineTwoFixedImpossible
import HC4.Newton.FirstContactCrossFacetAffineRRImpossible
import HC4.Newton.FirstContactCrossFacetEndpointTransition
import HC4.Newton.FirstContactCrossFacetCarrier
import HC4.Newton.FirstContactCrossFacetExit
import HC4.Newton.FirstContactCrossFacetArithmetic
import HC4.Valuation.AdaptiveAlignedSmithCanonicalTerminalRankThreeFirstContact
import HC4.Valuation.AdaptiveAlignedSmithCanonicalTerminalImpossible
import HC4.Valuation.AdaptiveAlignedSmithCanonicalRankOneTraceCollapse
import HC4.Valuation.AdaptiveAlignedSmithCanonicalZeroDefectCollisionEntry
import HC4.Valuation.AdaptiveAlignedSmithCanonicalZeroDefectTerminal