import HC4.Toric.InvariantSemigroup

/-!
# The branch character for the symmetric invariant semigroup

Besides the original grading, the difference `u₁-u₄` supplies a second
character on invariant exponent vectors.  It is positive on positive `r`
branches, negative on positive `s` branches, and zero exactly on the
`p,q`-subsemigroup.  This is the arithmetic core of the later simultaneous
character obstruction.
-/

namespace HC4.Toric

/-- The signed branch character `u₁-u₄`. -/
def branchCharacter (u : Exponent) : ℤ :=
  (u.x1 : ℤ) - (u.x4 : ℤ)

@[simp] theorem branchCharacter_pExponent :
    branchCharacter pExponent = 0 := by
  simp [branchCharacter, pExponent]

@[simp] theorem branchCharacter_qExponent :
    branchCharacter qExponent = 0 := by
  simp [branchCharacter, qExponent]

@[simp] theorem branchCharacter_rExponent (a b : ℕ) :
    branchCharacter (rExponent a b) = (b : ℤ) := by
  simp [branchCharacter, rExponent]

@[simp] theorem branchCharacter_sExponent (a b : ℕ) :
    branchCharacter (sExponent a b) = -(b : ℤ) := by
  simp [branchCharacter, sExponent]

@[simp] theorem branchCharacter_rBranch (a b i j k : ℕ) :
    branchCharacter (rBranch a b i j k) = (b : ℤ) * (k : ℤ) := by
  simp [branchCharacter, rBranch]

@[simp] theorem branchCharacter_sBranch (a b i j k : ℕ) :
    branchCharacter (sBranch a b i j k) = -((b : ℤ) * (k : ℤ)) := by
  simp [branchCharacter, sBranch]

/-- A positive-weight `r` branch has character zero only at parameter `k=0`. -/
theorem rBranch_parameter_zero_of_character_zero
    {a b i j k : ℕ} (hb : 0 < b)
    (hchar : branchCharacter (rBranch a b i j k) = 0) :
    k = 0 := by
  have hbZ : (0 : ℤ) < (b : ℤ) := by exact_mod_cast hb
  have hb0 : (b : ℤ) ≠ 0 := ne_of_gt hbZ
  have hmul : (b : ℤ) * (k : ℤ) = 0 := by
    simpa using hchar
  have hk0 : (k : ℤ) = 0 := (mul_eq_zero.mp hmul).resolve_left hb0
  exact_mod_cast hk0

/-- A positive-weight `s` branch has character zero only at parameter `k=0`. -/
theorem sBranch_parameter_zero_of_character_zero
    {a b i j k : ℕ} (hb : 0 < b)
    (hchar : branchCharacter (sBranch a b i j k) = 0) :
    k = 0 := by
  have hbZ : (0 : ℤ) < (b : ℤ) := by exact_mod_cast hb
  have hb0 : (b : ℤ) ≠ 0 := ne_of_gt hbZ
  have hmul : (b : ℤ) * (k : ℤ) = 0 := by
    have : -((b : ℤ) * (k : ℤ)) = 0 := by
      simpa using hchar
    linarith
  have hk0 : (k : ℤ) = 0 := (mul_eq_zero.mp hmul).resolve_left hb0
  exact_mod_cast hk0

/-- Positive `r` and positive `s` branches cannot have the same character. -/
theorem positive_rBranch_character_ne_positive_sBranch_character
    {a b i j k i' j' l : ℕ} (hb : 0 < b) (hk : 0 < k) (hl : 0 < l) :
    branchCharacter (rBranch a b i j k) ≠
      branchCharacter (sBranch a b i' j' l) := by
  have hbZ : (0 : ℤ) < (b : ℤ) := by exact_mod_cast hb
  have hkZ : (0 : ℤ) < (k : ℤ) := by exact_mod_cast hk
  have hlZ : (0 : ℤ) < (l : ℤ) := by exact_mod_cast hl
  rw [branchCharacter_rBranch, branchCharacter_sBranch]
  have hpos : (0 : ℤ) < (b : ℤ) * (k : ℤ) := mul_pos hbZ hkZ
  have hneg : -((b : ℤ) * (l : ℤ)) < 0 := by
    have : (0 : ℤ) < (b : ℤ) * (l : ℤ) := mul_pos hbZ hlZ
    linarith
  exact ne_of_gt (lt_trans hneg hpos)

/--
A balanced exponent with zero branch character belongs to the `p,q`
subsemigroup; equivalently its normal-form branch parameter is zero.
-/
theorem balanced_zero_character_normal_form
    {a b : ℕ} (ha : 0 < a) (hb : 0 < b) (hcop : a.Coprime b)
    {u : Exponent} (hBal : Balanced a b u) (hchar : branchCharacter u = 0) :
    ∃ i j : ℕ, u = rBranch a b i j 0 := by
  rcases (balanced_iff_normal_form ha hb hcop).mp hBal with hR | hS
  · rcases hR with ⟨i, j, k, hU⟩
    have hchar' : branchCharacter (rBranch a b i j k) = 0 := by
      rw [← hU]
      exact hchar
    have hk0 : k = 0 :=
      rBranch_parameter_zero_of_character_zero hb hchar'
    subst k
    exact ⟨i, j, hU⟩
  · rcases hS with ⟨i, j, k, hkPos, hU⟩
    have hchar' : branchCharacter (sBranch a b i j k) = 0 := by
      rw [← hU]
      exact hchar
    have hk0 : k = 0 :=
      sBranch_parameter_zero_of_character_zero hb hchar'
    exact False.elim ((Nat.ne_of_gt hkPos) hk0)

/-- The zero-character balanced exponents are generated by `p` and `q`. -/
theorem balanced_zero_character_as_generators
    {a b : ℕ} (ha : 0 < a) (hb : 0 < b) (hcop : a.Coprime b)
    {u : Exponent} (hBal : Balanced a b u) (hchar : branchCharacter u = 0) :
    ∃ i j : ℕ,
      u = Exponent.add (Exponent.scale i pExponent) (Exponent.scale j qExponent) := by
  rcases balanced_zero_character_normal_form ha hb hcop hBal hchar with ⟨i, j, hU⟩
  refine ⟨i, j, ?_⟩
  rw [hU, rBranch_as_generators]
  ext <;> simp [Exponent.add, Exponent.scale, rExponent]

end HC4.Toric
