import HC4.Toric.BranchCharacter

/-!
# Constant-character support rigidity

This module lifts the exponent-level branch character calculations to arbitrary
sets of balanced exponents.  It is the arithmetic support theorem needed when
a torus eigenfunction has a single character on its monomial support.

For positive character, every exponent lies on one common `r` level.  For
negative character, every exponent lies on one common positive `s` level.
Character zero is exactly the `p,q` cone.
-/

namespace HC4.Toric

/-- Every exponent in `S` lies on the same `r`-branch level `k`. -/
def OnRLevel (a b k : ℕ) (S : Set Exponent) : Prop :=
  ∀ u ∈ S, ∃ i j : ℕ, u = rBranch a b i j k

/-- Every exponent in `S` lies on the same `s`-branch level `k`. -/
def OnSLevel (a b k : ℕ) (S : Set Exponent) : Prop :=
  ∀ u ∈ S, ∃ i j : ℕ, u = sBranch a b i j k

/-- Every exponent in `S` lies in the subsemigroup generated by `p` and `q`. -/
def OnPQCone (S : Set Exponent) : Prop :=
  ∀ u ∈ S, ∃ i j : ℕ,
    u = Exponent.add (Exponent.scale i pExponent) (Exponent.scale j qExponent)

/-- Equality of `r`-branch characters forces equality of branch levels. -/
theorem rBranch_level_eq_of_character_eq
    {a b i j k i' j' k' : ℕ} (hb : 0 < b)
    (hchar : branchCharacter (rBranch a b i j k) =
      branchCharacter (rBranch a b i' j' k')) :
    k = k' := by
  have hb0 : (b : ℤ) ≠ 0 := by
    exact_mod_cast (Nat.ne_of_gt hb)
  have hmul : (b : ℤ) * ((k : ℤ) - (k' : ℤ)) = 0 := by
    rw [branchCharacter_rBranch, branchCharacter_rBranch] at hchar
    linarith
  have hdiff : (k : ℤ) - (k' : ℤ) = 0 :=
    (mul_eq_zero.mp hmul).resolve_left hb0
  have hkZ : (k : ℤ) = (k' : ℤ) := sub_eq_zero.mp hdiff
  exact_mod_cast hkZ

/-- Equality of `s`-branch characters forces equality of branch levels. -/
theorem sBranch_level_eq_of_character_eq
    {a b i j k i' j' k' : ℕ} (hb : 0 < b)
    (hchar : branchCharacter (sBranch a b i j k) =
      branchCharacter (sBranch a b i' j' k')) :
    k = k' := by
  have hb0 : (b : ℤ) ≠ 0 := by
    exact_mod_cast (Nat.ne_of_gt hb)
  have hmul : (b : ℤ) * ((k : ℤ) - (k' : ℤ)) = 0 := by
    rw [branchCharacter_sBranch, branchCharacter_sBranch] at hchar
    linarith
  have hdiff : (k : ℤ) - (k' : ℤ) = 0 :=
    (mul_eq_zero.mp hmul).resolve_left hb0
  have hkZ : (k : ℤ) = (k' : ℤ) := sub_eq_zero.mp hdiff
  exact_mod_cast hkZ

/-- A balanced exponent of positive branch character lies on a positive `r` branch. -/
theorem positive_character_normal_form
    {a b : ℕ} (ha : 0 < a) (hb : 0 < b) (hcop : a.Coprime b)
    {u : Exponent} (hBal : Balanced a b u)
    (hpos : 0 < branchCharacter u) :
    ∃ i j k : ℕ, 0 < k ∧ u = rBranch a b i j k := by
  rcases (balanced_iff_normal_form ha hb hcop).mp hBal with hR | hS
  · rcases hR with ⟨i, j, k, hU⟩
    have hkPos : 0 < k := by
      by_contra hkNot
      have hk0 : k = 0 := Nat.eq_zero_of_not_pos hkNot
      subst k
      rw [hU, branchCharacter_rBranch] at hpos
      simp at hpos
    exact ⟨i, j, k, hkPos, hU⟩
  · rcases hS with ⟨i, j, k, hkPos, hU⟩
    have hbZ : (0 : ℤ) < (b : ℤ) := by exact_mod_cast hb
    have hkZ : (0 : ℤ) < (k : ℤ) := by exact_mod_cast hkPos
    rw [hU, branchCharacter_sBranch] at hpos
    have hprod : (0 : ℤ) < (b : ℤ) * (k : ℤ) := mul_pos hbZ hkZ
    linarith

/-- A balanced exponent of negative branch character lies on a positive `s` branch. -/
theorem negative_character_normal_form
    {a b : ℕ} (ha : 0 < a) (hb : 0 < b) (hcop : a.Coprime b)
    {u : Exponent} (hBal : Balanced a b u)
    (hneg : branchCharacter u < 0) :
    ∃ i j k : ℕ, 0 < k ∧ u = sBranch a b i j k := by
  rcases (balanced_iff_normal_form ha hb hcop).mp hBal with hR | hS
  · rcases hR with ⟨i, j, k, hU⟩
    rw [hU, branchCharacter_rBranch] at hneg
    have hbNonneg : (0 : ℤ) ≤ (b : ℤ) := by positivity
    have hkNonneg : (0 : ℤ) ≤ (k : ℤ) := by positivity
    have hprod : (0 : ℤ) ≤ (b : ℤ) * (k : ℤ) := mul_nonneg hbNonneg hkNonneg
    linarith
  · rcases hS with ⟨i, j, k, hkPos, hU⟩
    exact ⟨i, j, k, hkPos, hU⟩

/-- Positive constant character on a nonempty balanced support fixes one positive `r` level. -/
theorem positive_constant_character_support
    {a b : ℕ} (ha : 0 < a) (hb : 0 < b) (hcop : a.Coprime b)
    {S : Set Exponent} {c : ℤ} (hc : 0 < c) (hS : S.Nonempty)
    (hBal : ∀ u ∈ S, Balanced a b u)
    (hchar : ∀ u ∈ S, branchCharacter u = c) :
    ∃ k : ℕ, 0 < k ∧ OnRLevel a b k S := by
  rcases hS with ⟨u₀, hu₀⟩
  have hu₀Pos : 0 < branchCharacter u₀ := by
    rw [hchar u₀ hu₀]
    exact hc
  rcases positive_character_normal_form ha hb hcop (hBal u₀ hu₀) hu₀Pos with
    ⟨i₀, j₀, k₀, hk₀, hu₀Form⟩
  refine ⟨k₀, hk₀, ?_⟩
  intro u hu
  have huPos : 0 < branchCharacter u := by
    rw [hchar u hu]
    exact hc
  rcases positive_character_normal_form ha hb hcop (hBal u hu) huPos with
    ⟨i, j, k, hk, huForm⟩
  have hsame : branchCharacter (rBranch a b i j k) =
      branchCharacter (rBranch a b i₀ j₀ k₀) := by
    calc
      branchCharacter (rBranch a b i j k) = branchCharacter u := by rw [huForm]
      _ = c := hchar u hu
      _ = branchCharacter u₀ := (hchar u₀ hu₀).symm
      _ = branchCharacter (rBranch a b i₀ j₀ k₀) := by rw [hu₀Form]
  have hkEq : k = k₀ := rBranch_level_eq_of_character_eq hb hsame
  subst k
  exact ⟨i, j, huForm⟩

/-- Negative constant character on a nonempty balanced support fixes one positive `s` level. -/
theorem negative_constant_character_support
    {a b : ℕ} (ha : 0 < a) (hb : 0 < b) (hcop : a.Coprime b)
    {S : Set Exponent} {c : ℤ} (hc : c < 0) (hS : S.Nonempty)
    (hBal : ∀ u ∈ S, Balanced a b u)
    (hchar : ∀ u ∈ S, branchCharacter u = c) :
    ∃ k : ℕ, 0 < k ∧ OnSLevel a b k S := by
  rcases hS with ⟨u₀, hu₀⟩
  have hu₀Neg : branchCharacter u₀ < 0 := by
    rw [hchar u₀ hu₀]
    exact hc
  rcases negative_character_normal_form ha hb hcop (hBal u₀ hu₀) hu₀Neg with
    ⟨i₀, j₀, k₀, hk₀, hu₀Form⟩
  refine ⟨k₀, hk₀, ?_⟩
  intro u hu
  have huNeg : branchCharacter u < 0 := by
    rw [hchar u hu]
    exact hc
  rcases negative_character_normal_form ha hb hcop (hBal u hu) huNeg with
    ⟨i, j, k, hk, huForm⟩
  have hsame : branchCharacter (sBranch a b i j k) =
      branchCharacter (sBranch a b i₀ j₀ k₀) := by
    calc
      branchCharacter (sBranch a b i j k) = branchCharacter u := by rw [huForm]
      _ = c := hchar u hu
      _ = branchCharacter u₀ := (hchar u₀ hu₀).symm
      _ = branchCharacter (sBranch a b i₀ j₀ k₀) := by rw [hu₀Form]
  have hkEq : k = k₀ := sBranch_level_eq_of_character_eq hb hsame
  subst k
  exact ⟨i, j, huForm⟩

/-- Character-zero balanced support lies entirely in the `p,q` cone. -/
theorem zero_character_support
    {a b : ℕ} (ha : 0 < a) (hb : 0 < b) (hcop : a.Coprime b)
    {S : Set Exponent}
    (hBal : ∀ u ∈ S, Balanced a b u)
    (hchar : ∀ u ∈ S, branchCharacter u = 0) :
    OnPQCone S := by
  intro u hu
  exact balanced_zero_character_as_generators ha hb hcop (hBal u hu) (hchar u hu)

end HC4.Toric
