#!/usr/bin/env python3
"""Generate deterministic documentation for the HC4 Lean source tree.

The generator is intentionally lightweight and dependency-free.  It is not a
Lean parser; Lean remains the authority.  The script extracts navigation data
that is stable and useful for repository-scale proof work:

* every local Lean module and path;
* direct local and external imports;
* reverse local importers;
* the first module-doc heading;
* A18/A19 labels mentioned by the module;
* declaration spellings visible at declaration starts;
* declaration spellings that occur in more than one module.

Run:
    python3 tools/generate_proof_inventory.py

Check committed output without changing files:
    python3 tools/generate_proof_inventory.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


IMPORT_RE = re.compile(r"^\s*import\s+([A-Za-z0-9_.'-]+)\s*$", re.MULTILINE)
LABEL_RE = re.compile(r"\bA(?:18|19)(?:\.\d+)+(?:[A-Za-z]+)?\b")
DECL_RE = re.compile(
    r"^\s*"
    r"(?:(?:private|protected|noncomputable|unsafe|partial)\s+)*"
    r"(theorem|lemma|def|abbrev|structure|inductive|class|opaque|axiom)\s+"
    r"([A-Za-z_][A-Za-z0-9_'.]*)\b",
    re.MULTILINE,
)
MODULE_DOC_RE = re.compile(r"/-!(.*?)-/", re.DOTALL)
HEADING_RE = re.compile(r"^\s*#\s+(.+?)\s*$", re.MULTILINE)


@dataclass(frozen=True)
class Declaration:
    kind: str
    name: str


@dataclass(frozen=True)
class ModuleInfo:
    module: str
    path: str
    title: str
    labels: tuple[str, ...]
    imports: tuple[str, ...]
    declarations: tuple[Declaration, ...]


def module_name(root: Path, path: Path) -> str:
    rel = path.relative_to(root)
    if rel.as_posix() == "HC4.lean":
        return "HC4"
    no_suffix = rel.with_suffix("")
    return ".".join(no_suffix.parts)


def module_title(text: str) -> str:
    match = MODULE_DOC_RE.search(text)
    if match is None:
        return "(no module-doc heading)"
    heading = HEADING_RE.search(match.group(1))
    if heading is None:
        return "(module doc present; no heading)"
    return " ".join(heading.group(1).split())


def parse_module(root: Path, path: Path) -> ModuleInfo:
    text = path.read_text(encoding="utf-8")
    declarations = tuple(
        Declaration(kind=kind, name=name) for kind, name in DECL_RE.findall(text)
    )
    return ModuleInfo(
        module=module_name(root, path),
        path=path.relative_to(root).as_posix(),
        title=module_title(text),
        labels=tuple(sorted(set(LABEL_RE.findall(text)))),
        imports=tuple(IMPORT_RE.findall(text)),
        declarations=declarations,
    )


def collect_modules(root: Path) -> list[ModuleInfo]:
    paths: list[Path] = []
    root_module = root / "HC4.lean"
    if root_module.is_file():
        paths.append(root_module)
    source_root = root / "HC4"
    if source_root.is_dir():
        paths.extend(sorted(source_root.rglob("*.lean")))
    return [parse_module(root, path) for path in paths]


def render_module_index(modules: list[ModuleInfo]) -> str:
    local_names = {m.module for m in modules}
    reverse: dict[str, list[str]] = defaultdict(list)
    for module in modules:
        for imported in module.imports:
            if imported in local_names:
                reverse[imported].append(module.module)

    by_area: dict[str, list[ModuleInfo]] = defaultdict(list)
    for module in modules:
        parts = module.path.split("/")
        area = "root" if len(parts) == 1 else parts[1] if len(parts) > 2 else "HC4 root"
        by_area[area].append(module)

    lines = [
        "# Generated Lean module index",
        "",
        "**Generated by `tools/generate_proof_inventory.py`. Do not edit by hand.**",
        "",
        f"Modules indexed: **{len(modules)}**.",
        "",
        "Each section records the module's own documentation heading, direct imports,",
        "reverse importers, A18/A19 labels, and declarations detected at declaration starts.",
        "Lean itself remains authoritative for elaborated names and dependencies.",
        "",
    ]

    for area in sorted(by_area, key=lambda value: (value != "root", value.lower())):
        lines.extend([f"## Area: `{area}`", ""])
        for module in sorted(by_area[area], key=lambda item: item.module):
            local_imports = [name for name in module.imports if name in local_names]
            external_imports = [name for name in module.imports if name not in local_names]
            importers = sorted(reverse.get(module.module, []))
            lines.extend(
                [
                    f"### `{module.module}`",
                    "",
                    f"- Path: `{module.path}`",
                    f"- Purpose: {module.title}",
                    "- A-labels: "
                    + (", ".join(f"`{label}`" for label in module.labels) if module.labels else "none detected"),
                    "- Local imports: "
                    + (", ".join(f"`{name}`" for name in local_imports) if local_imports else "none"),
                    "- External imports: "
                    + (", ".join(f"`{name}`" for name in external_imports) if external_imports else "none"),
                    "- Imported by local modules: "
                    + (", ".join(f"`{name}`" for name in importers) if importers else "none"),
                    "- Declarations: "
                    + (
                        ", ".join(f"`{decl.kind} {decl.name}`" for decl in module.declarations)
                        if module.declarations
                        else "none detected"
                    ),
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def render_declaration_index(modules: list[ModuleInfo]) -> str:
    occurrences: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for module in modules:
        for declaration in module.declarations:
            occurrences[declaration.name].append((module.module, declaration.kind))

    lines = [
        "# Generated declaration spelling index",
        "",
        "**Generated by `tools/generate_proof_inventory.py`. Do not edit by hand.**",
        "",
        "This is a source-navigation index, not a substitute for Lean name resolution.",
        "A declaration written inside a namespace may have a different fully-qualified name",
        "from its textual spelling below. Repeated spellings are therefore **search prompts**",
        "rather than automatic proof of an environment collision.",
        "",
        f"Distinct declaration spellings indexed: **{len(occurrences)}**.",
        "",
        "## Repeated declaration spellings",
        "",
    ]

    repeated = {name: values for name, values in occurrences.items() if len(values) > 1}
    if not repeated:
        lines.append("No repeated declaration spellings detected.")
    else:
        for name in sorted(repeated):
            rendered = ", ".join(
                f"`{kind}` in `{module}`" for module, kind in sorted(repeated[name])
            )
            lines.append(f"- `{name}` — {rendered}")

    lines.extend(["", "## All declaration spellings", ""])
    for name in sorted(occurrences):
        rendered = ", ".join(
            f"`{kind}` in `{module}`" for module, kind in sorted(occurrences[name])
        )
        lines.append(f"- `{name}` — {rendered}")

    return "\n".join(lines).rstrip() + "\n"


def render_import_edges(modules: list[ModuleInfo]) -> str:
    local_names = {m.module for m in modules}
    lines = [
        "# Generated local import edges",
        "",
        "**Generated by `tools/generate_proof_inventory.py`. Do not edit by hand.**",
        "",
        "Each entry lists direct imports that resolve to another Lean module in this checkout.",
        "This is the mechanically derived proof-DAG adjacency list used alongside the",
        "human architecture guide.",
        "",
    ]
    for module in sorted(modules, key=lambda item: item.module):
        local_imports = sorted(name for name in module.imports if name in local_names)
        lines.append(f"- `{module.module}`")
        for imported in local_imports:
            lines.append(f"  - `{imported}`")
        if not local_imports:
            lines.append("  - _(no local imports)_")
    return "\n".join(lines).rstrip() + "\n"


def expected_outputs(root: Path, modules: list[ModuleInfo]) -> dict[Path, str]:
    generated = root / "docs" / "generated"
    return {
        generated / "LEAN_MODULE_INDEX.md": render_module_index(modules),
        generated / "DECLARATION_INDEX.md": render_declaration_index(modules),
        generated / "LOCAL_IMPORT_EDGES.md": render_import_edges(modules),
    }


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path}")


def check_outputs(outputs: dict[Path, str]) -> int:
    stale: list[Path] = []
    for path, expected in outputs.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)
    if not stale:
        print("proof inventory is current")
        return 0
    print("proof inventory is stale; regenerate with:", file=sys.stderr)
    print("  python3 tools/generate_proof_inventory.py", file=sys.stderr)
    for path in stale:
        print(f"  stale/missing: {path}", file=sys.stderr)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files match the source tree without rewriting them",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root (defaults to the parent of tools/)",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    modules = collect_modules(root)
    if not modules:
        print(f"no Lean modules found under {root}", file=sys.stderr)
        return 2

    outputs = expected_outputs(root, modules)
    if args.check:
        return check_outputs(outputs)
    write_outputs(outputs)
    print(f"indexed {len(modules)} Lean modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
